title: OpenDataHub
email: opendatahub@redhat.com
description: >
  redirect to opendatahub.io

# Build settings
markdown: kramdown

permalink: /news/:year-:month-:day/:title:output_ext

plugins:
  - jekyll-redirect-from

exclude:
  - design
  - "README.md"
  - .idea